name: Deploy to GH pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 8.0.x
          include-prerelease: true
      - name : Install WASM-Tools
        run: dotnet workload install wasm-tools
      - name: Publish .NET Core Project
        run: dotnet publish MiniBlazorDemo.csproj -c Release -o release
      - name: Patch base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1.1.0
        with:
            html_path: 'release/wwwroot/index.html'
            base_href: '/wasm_mini_demo_blazor/'
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot